spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      acks: all
      properties:
        enable:
          idempotence: true
        max:
          in:
            flight:
              request:
                per:
                  connection: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/testRealm
      client:
        registration:
          travel-plan-service-client:
            provider: keycloak
            client-id: my-client
            client-secret: vGng14JZzF4sKa5Zw0hAodViJAGwAIte
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:9090/realms/testRealm/protocol/openid-connect/token
  application:
    name: travel-plans-service
  cloud:
    openfeign:
      client:
        config:
          attraction-service:
            connectTimeout: 10000   # Таймаут установки соединения (10 сек)
            readTimeout: 60000      # Таймаут ожидания ответа (60 сек)
            error-decoder: ru.jg.travelplans.handler.AttractionErrorDecoder
  datasource:
    url: jdbc:h2:mem:travel
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  #      http://localhost:8081/h2-console

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakerevents  # Чтобы был доступ к эндпоинтов актуатора нужно их открыть

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

resilience4j:
  circuitbreaker:
    instances:
      attractionCB:
        failureRateThreshold: 50                  # 50% неудачных запросов - CB срабатывает
        slowCallRateThreshold: 50                 # 50% медленных запросов - CB срабатывает
        slowCallDurationThreshold: 2s             # Запрос дольше 2 сек считается медленным
        slidingWindowType: count_based            # Окно ошибок основано на количестве запросов
        slidingWindowSize: 10                     # Анализируем последние 10 запросов
        minimumNumberOfCalls: 5                   # Минимум 5 вызовов перед изменением состояния
        waitDurationInOpenState: 10s              # CB остается открытым 10 сек перед проверкой
        permittedNumberOfCallsInHalfOpenState: 3  # 3 запроса в Half-Open перед закрытием
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true             # Добавляет состояние CB в /actuator/health
        event-consumer-buffer-size: 10            # Размер буфера событий
    circuit-breaker-aspect-order: 2               # Порядок выполненеия аспектов
  retry:
    instances:
      attractionCB:
        maxAttempts: 3                            # Максимальное количество попыток
        waitDuration: 30s                          # Время ожидания между попытками
    retry-aspect-order: 1

travel-plan:
  request-topic: attraction-created-event-topic

logging:
  level:
    org.springframework.security: DEBUG