spring:
  application:
    name: travel-plans-service
  cloud:
    openfeign:
      client:
        config:
          attraction-service:
            connectTimeout: 10000  # Таймаут установки соединения (10 сек)
            readTimeout: 60000  # Таймаут ожидания ответа (60 сек)
            error-decoder: ru.jg.travelplans.handler.AttractionErrorDecoder
  datasource:
    url: jdbc:h2:mem:travel
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  #      http://localhost:8081/h2-console

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

application:
  config:
    attraction-url: http://attraction-service/api/v1/attractions