spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: travel-service
          uri: lb://travel-plans-service
          predicates:
            - Path=/api/v1/plans/**
            - Method=GET
          filters:
            - JwtAuthFilter
        - id: auth-server
          uri: lb://authorization-server
          predicates:
            - Path=/auth/**
  application:
    name: api-gateway

server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

auth:
  server:
    validate-token-url: http://authorization-server/auth/validate