spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/testRealm
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: attraction-service
          uri: lb://attraction-service
          predicates:
            - Path=/api/v1/attractions/**
            - Method=GET
        - id: travel-service
          uri: lb://travel-plans-service
          predicates:
            - Path=/api/v1/plans/**
            - Method=GET
      default-filters: TokenRelay=
  application:
    name: api-gateway

server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

auth:
  server:
    validate-token-url: http://authorization-server/auth/validate

logging:
  level:
    org.springframework.security: DEBUG