spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9999

jwt:
  secretKey: "MySuperPuperSecretKey12345678910"
